# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-adonis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          
      -  name: npm production
         env:
            PORT: ${{ secrets.PORT }}
            HOST: ${{ secrets.HOST }}
            NODE_ENV: ${{ secrets.NODE_ENV }}
            APP_KEY: ${{ secrets.APP_KEY }}
            DRIVE_DISK: ${{ secrets.DRIVE_DISK }}
            DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
            PG_HOST: ${{ secrets.PG_HOST }}
            PG_PORT: ${{ secrets.PG_PORT }}
            PG_USER: ${{ secrets.PG_USER }}
            PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
            PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
            MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            CACHE_VIEWS: ${{ secrets.CACHE_VIEWS }}
         run: |
            npm ci --production
            node server.js
         working-directory: build
  
      - name: exec migrations
        env:
            PORT: ${{ secrets.PORT }}
            HOST: ${{ secrets.HOST }}
            NODE_ENV: ${{ secrets.NODE_ENV }}
            APP_KEY: ${{ secrets.APP_KEY }}
            DRIVE_DISK: ${{ secrets.DRIVE_DISK }}
            DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
            PG_HOST: ${{ secrets.PG_HOST }}
            PG_PORT: ${{ secrets.PG_PORT }}
            PG_USER: ${{ secrets.PG_USER }}
            PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
            PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
            MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            CACHE_VIEWS: ${{ secrets.CACHE_VIEWS }}
        run: node ace migration:run
        working-directory: build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: adonis-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: adonis-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-adonis'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D61AB75E0E3A4162999F997A21BFEE8B }}
          package: ./build
